"""Conservative clip targets. Each number is the low end of the requested range."""

PLAN = [
    (
        "Ancient Egypt / Archaeology",
        "ancient egypt",
        [
            ("Egyptian Pyramids", 40),
            ("Great Sphinx", 30),
            ("Giza Plateau", 20),
            ("Egyptian Desert", 25),
            ("Desert Drone Footage", 20),
            ("Ancient Egyptian Temples", 30),
            ("Egyptian Ruins", 25),
            ("Ancient Stone Ruins", 20),
            ("Archaeological Ruins", 20),
            ("Ancient Columns", 10),
            ("Ancient Stone Walls", 10),
            ("Egyptian Tomb Interior", 20),
            ("Ancient Tomb", 15),
            ("Burial Chamber", 10),
            ("Underground Stone Chamber", 10),
            ("Ancient Stone Tunnel", 10),
            ("Dark Ancient Corridor", 8),
            ("Ancient Underground Ruins", 10),
            ("Stone Steps", 5),
            ("Ancient Doorway", 5),
            ("Ancient Temple Interior", 15),
            ("Nile River", 15),
            ("Hieroglyphics", 20),
            ("Egyptian Wall Carvings", 15),
            ("Egyptian Statues", 15),
            ("Pharaoh Statues", 10),
            ("Sarcophagus", 15),
            ("Egyptian Mummy", 20),
            ("Mummified Body", 10),
            ("Ancient Skeleton", 10),
            ("Ancient Skull", 5),
            ("Ancient Bones", 5),
            ("Ancient Pottery", 10),
            ("Ancient Jewelry", 5),
            ("Ancient Coins", 5),
            ("Ancient Stone Tablet", 10),
            ("Papyrus", 10),
            ("Ancient Manuscript", 10),
            ("Old Scroll", 8),
            ("Archaeologist Excavating", 15),
            ("Archaeologist Brushing Artifact", 10),
            ("Archaeologists At Dig Site", 15),
            ("Archaeologist Examining Artifact", 10),
            ("Archaeologist Inside Tomb", 8),
            ("Skeleton Excavation", 8),
            ("Desert Excavation", 10),
            ("Artifact Discovery", 8),
            ("Museum Artifacts", 10),
            ("Egyptian Museum Exhibit", 10),
            ("Museum Mummy", 8),
            ("Scientist Examining Artifact", 8),
            ("Laboratory Artifact Analysis", 5),
            ("Microscope Laboratory", 5),
            ("CT Scanner", 5),
            ("X-Ray Scan", 5),
            ("Ground Penetrating Radar", 8),
            ("Laser Scanner", 5),
            ("3D Scanner", 5),
            ("Drone Scanning Ruins", 5),
            ("Cave Interior", 15),
            ("Cave Entrance", 10),
            ("Torch In Cave", 5),
            ("Underground Ruins Exploration", 8),
            ("Archaeologist Walking Through Ruins", 8),
        ],
    ),
    (
        "Volcanoes / Earth / Geology",
        "geology",
        [
            ("Volcano", 30),
            ("Volcano Eruption", 40),
            ("Explosive Eruption", 20),
            ("Lava Flow", 35),
            ("Flowing Lava Close-Up", 20),
            ("Lava Fountain", 15),
            ("Lava Lake", 10),
            ("Lava Entering Ocean", 10),
            ("Volcanic Crater", 20),
            ("Volcano Smoke", 15),
            ("Volcanic Ash", 10),
            ("Volcanic Ash Cloud", 15),
            ("Volcanic Rock", 8),
            ("Cooling Lava", 8),
            ("Volcano Drone Footage", 20),
            ("Geyser", 15),
            ("Hot Spring", 15),
            ("Geothermal Area", 15),
            ("Steam Vent", 10),
            ("Earthquake Damage", 25),
            ("Shaking Buildings", 10),
            ("Cracked Road", 10),
            ("Cracked Ground", 10),
            ("Ground Rupture", 10),
            ("Collapsed Buildings", 15),
            ("Seismograph", 8),
            ("Seismic Monitoring Equipment", 8),
            ("Scientist Monitoring Earthquake", 5),
            ("Fault Line", 15),
            ("Rock Fault", 8),
            ("Rock Layers", 15),
            ("Exposed Geological Layers", 15),
            ("Canyon", 20),
            ("Cliff", 15),
            ("Mountain Range", 25),
            ("Rocky Mountains", 20),
            ("Mountain Drone Footage", 20),
            ("Desert Mountains", 15),
            ("Eroded Rock Formations", 15),
            ("Unusual Rock Formations", 15),
            ("Cave Interior", 20),
            ("Large Cave", 15),
            ("Underground Cave", 15),
            ("Lava Tube", 10),
            ("Crystal Cave", 8),
            ("Underground River", 10),
            ("Sinkhole", 15),
            ("Giant Sinkhole", 10),
            ("Landslide", 15),
            ("Rockslide", 10),
            ("Avalanche", 15),
            ("Glacier", 25),
            ("Glacier Calving", 15),
            ("Melting Glacier", 10),
            ("Iceberg", 20),
            ("Iceberg Underwater", 10),
            ("Ice Sheet", 15),
            ("Frozen Landscape", 15),
            ("Antarctica", 20),
            ("Arctic Landscape", 15),
            ("Geological Drilling", 10),
            ("Drilling Rig", 15),
            ("Core Sample", 5),
            ("Rock Core Sample", 5),
            ("Geologist Fieldwork", 15),
            ("Geologist Collecting Rocks", 10),
            ("Geologist Using Hammer", 8),
            ("Scientist Examining Rocks", 8),
            ("Rock Laboratory", 5),
            ("Mineral Samples", 8),
            ("Fossil", 10),
            ("Fossil Excavation", 10),
            ("Meteorite", 8),
            ("Impact Crater", 15),
            ("Aerial Crater Footage", 10),
            ("Earth From Space", 20),
            ("Satellite Earth Footage", 15),
            ("Thermal Imaging", 8),
            ("Soil Sampling", 5),
            ("Underground Mine", 10),
        ],
    ),
    (
        "Deep Ocean / Ocean Mysteries",
        "deep ocean",
        [
            ("Ocean Surface", 30),
            ("Open Ocean", 25),
            ("Ocean Waves", 25),
            ("Rough Ocean", 15),
            ("Stormy Ocean", 15),
            ("Calm Ocean", 15),
            ("Ocean At Night", 10),
            ("Ocean Drone Footage", 20),
            ("Underwater Ocean", 30),
            ("Deep Underwater", 30),
            ("Dark Ocean", 25),
            ("Underwater Darkness", 20),
            ("Blue Underwater", 20),
            ("Ocean Floor", 35),
            ("Sandy Seafloor", 15),
            ("Rocky Seafloor", 15),
            ("Deep Seafloor", 20),
            ("Underwater Rocks", 15),
            ("Underwater Cliffs", 10),
            ("Underwater Canyon", 10),
            ("Ocean Trench", 20),
            ("Underwater Mountain", 10),
            ("Underwater Volcano", 15),
            ("Hydrothermal Vent", 15),
            ("Black Smoker", 10),
            ("Bubbles Underwater", 10),
            ("Underwater Gas Bubbles", 8),
            ("Underwater Cave", 15),
            ("Underwater Cave Entrance", 10),
            ("Blue Hole", 10),
            ("ROV Underwater", 35),
            ("ROV Descending", 15),
            ("ROV Camera", 10),
            ("ROV Robot Arm", 10),
            ("Underwater Drone", 15),
            ("Submersible", 20),
            ("Submersible Underwater", 20),
            ("Submarine Underwater", 15),
            ("Submarine Surfacing", 8),
            ("Research Ship", 25),
            ("Ocean Research Vessel", 20),
            ("Scientists On Research Ship", 15),
            ("Scientists Launching ROV", 8),
            ("Scientists Recovering ROV", 8),
            ("Marine Scientists", 10),
            ("Ocean Laboratory", 8),
            ("Water Sample Collection", 8),
            ("Sediment Sample", 5),
            ("Underwater Camera", 15),
            ("Underwater Lights", 10),
            ("Divers Underwater", 15),
            ("Deep Sea Diver", 10),
            ("Shipwreck", 20),
            ("Old Shipwreck", 15),
            ("Sunken Ship", 15),
            ("Underwater Aircraft Wreck", 5),
            ("ROV Exploring Shipwreck", 10),
            ("Underwater Ruins", 10),
            ("Underwater Statue", 5),
            ("Submerged Structure", 8),
            ("Coral Reef", 20),
            ("Deep Sea Coral", 10),
            ("Kelp Forest", 10),
            ("School Of Fish", 15),
            ("Shark", 20),
            ("Great White Shark", 15),
            ("Whale Shark", 10),
            ("Whale", 15),
            ("Sperm Whale", 10),
            ("Orca", 10),
            ("Dolphin", 10),
            ("Octopus", 15),
            ("Giant Octopus", 8),
            ("Squid", 10),
            ("Giant Squid", 8),
            ("Jellyfish", 15),
            ("Deep Sea Jellyfish", 10),
            ("Anglerfish", 10),
            ("Deep Sea Fish", 20),
            ("Bioluminescent Creatures", 15),
            ("Bioluminescence Underwater", 15),
            ("Deep Sea Crab", 8),
            ("Giant Isopod", 5),
            ("Sea Cucumber", 5),
            ("Plankton", 8),
            ("Marine Snow", 8),
            ("Ocean Buoy", 8),
            ("Underwater Pipeline", 8),
            ("Undersea Cable", 8),
            ("Offshore Oil Rig", 15),
            ("Iceberg Underwater", 10),
            ("Underwater Ice", 10),
            ("Antarctic Ocean", 15),
            ("Arctic Ocean", 15),
            ("ROV Picking Up Object", 8),
            ("Underwater Sediment Cloud", 8),
            ("Flashlight Underwater", 8),
            ("Object On Seafloor", 10),
            ("Empty Deep Ocean", 15),
            ("Research Vessel At Night", 8),
        ],
    ),
]
