"""Clip targets. Each number is the high end of the requested range. One unique source per clip."""

PLAN = [
    (
        "Ancient Egypt / Archaeology",
        "ancient egypt",
        [
            ("Egyptian Pyramids", 50),
            ("Great Sphinx", 40),
            ("Giza Plateau", 30),
            ("Egyptian Desert", 35),
            ("Desert Drone Footage", 30),
            ("Ancient Egyptian Temples", 40),
            ("Egyptian Ruins", 35),
            ("Ancient Stone Ruins", 30),
            ("Archaeological Ruins", 30),
            ("Ancient Columns", 15),
            ("Ancient Stone Walls", 15),
            ("Egyptian Tomb Interior", 30),
            ("Ancient Tomb", 20),
            ("Burial Chamber", 15),
            ("Underground Stone Chamber", 15),
            ("Ancient Stone Tunnel", 15),
            ("Dark Ancient Corridor", 12),
            ("Ancient Underground Ruins", 15),
            ("Stone Steps", 10),
            ("Ancient Doorway", 10),
            ("Ancient Temple Interior", 20),
            ("Nile River", 20),
            ("Hieroglyphics", 30),
            ("Egyptian Wall Carvings", 20),
            ("Egyptian Statues", 20),
            ("Pharaoh Statues", 15),
            ("Sarcophagus", 20),
            ("Egyptian Mummy", 30),
            ("Mummified Body", 15),
            ("Ancient Skeleton", 15),
            ("Ancient Skull", 10),
            ("Ancient Bones", 10),
            ("Ancient Pottery", 15),
            ("Ancient Jewelry", 10),
            ("Ancient Coins", 10),
            ("Ancient Stone Tablet", 15),
            ("Papyrus", 15),
            ("Ancient Manuscript", 15),
            ("Old Scroll", 12),
            ("Archaeologist Excavating", 20),
            ("Archaeologist Brushing Artifact", 15),
            ("Archaeologists At Dig Site", 20),
            ("Archaeologist Examining Artifact", 15),
            ("Archaeologist Inside Tomb", 12),
            ("Skeleton Excavation", 12),
            ("Desert Excavation", 15),
            ("Artifact Discovery", 12),
            ("Museum Artifacts", 15),
            ("Egyptian Museum Exhibit", 15),
            ("Museum Mummy", 12),
            ("Scientist Examining Artifact", 12),
            ("Laboratory Artifact Analysis", 10),
            ("Microscope Laboratory", 10),
            ("CT Scanner", 8),
            ("X-Ray Scan", 8),
            ("Ground Penetrating Radar", 12),
            ("Laser Scanner", 10),
            ("3D Scanner", 10),
            ("Drone Scanning Ruins", 10),
            ("Cave Interior", 20),
            ("Cave Entrance", 15),
            ("Torch In Cave", 10),
            ("Underground Ruins Exploration", 12),
            ("Archaeologist Walking Through Ruins", 12),
        ],
    ),
    (
        "Volcanoes / Earth / Geology",
        "geology",
        [
            ("Volcano", 40),
            ("Volcano Eruption", 50),
            ("Explosive Eruption", 30),
            ("Lava Flow", 45),
            ("Flowing Lava Close-Up", 30),
            ("Lava Fountain", 20),
            ("Lava Lake", 15),
            ("Lava Entering Ocean", 15),
            ("Volcanic Crater", 30),
            ("Volcano Smoke", 20),
            ("Volcanic Ash", 15),
            ("Volcanic Ash Cloud", 20),
            ("Volcanic Rock", 12),
            ("Cooling Lava", 12),
            ("Volcano Drone Footage", 30),
            ("Geyser", 20),
            ("Hot Spring", 20),
            ("Geothermal Area", 20),
            ("Steam Vent", 15),
            ("Earthquake Damage", 35),
            ("Shaking Buildings", 15),
            ("Cracked Road", 15),
            ("Cracked Ground", 15),
            ("Ground Rupture", 15),
            ("Collapsed Buildings", 20),
            ("Seismograph", 12),
            ("Seismic Monitoring Equipment", 12),
            ("Scientist Monitoring Earthquake", 10),
            ("Fault Line", 20),
            ("Rock Fault", 12),
            ("Rock Layers", 20),
            ("Exposed Geological Layers", 20),
            ("Canyon", 30),
            ("Cliff", 20),
            ("Mountain Range", 35),
            ("Rocky Mountains", 30),
            ("Mountain Drone Footage", 30),
            ("Desert Mountains", 20),
            ("Eroded Rock Formations", 20),
            ("Unusual Rock Formations", 20),
            ("Cave Interior", 30),
            ("Large Cave", 20),
            ("Underground Cave", 20),
            ("Lava Tube", 15),
            ("Crystal Cave", 12),
            ("Underground River", 15),
            ("Sinkhole", 20),
            ("Giant Sinkhole", 15),
            ("Landslide", 20),
            ("Rockslide", 15),
            ("Avalanche", 20),
            ("Glacier", 35),
            ("Glacier Calving", 20),
            ("Melting Glacier", 15),
            ("Iceberg", 30),
            ("Iceberg Underwater", 15),
            ("Ice Sheet", 20),
            ("Frozen Landscape", 20),
            ("Antarctica", 30),
            ("Arctic Landscape", 20),
            ("Geological Drilling", 15),
            ("Drilling Rig", 20),
            ("Core Sample", 10),
            ("Rock Core Sample", 10),
            ("Geologist Fieldwork", 20),
            ("Geologist Collecting Rocks", 15),
            ("Geologist Using Hammer", 12),
            ("Scientist Examining Rocks", 12),
            ("Rock Laboratory", 10),
            ("Mineral Samples", 12),
            ("Fossil", 15),
            ("Fossil Excavation", 15),
            ("Meteorite", 12),
            ("Impact Crater", 20),
            ("Aerial Crater Footage", 15),
            ("Earth From Space", 30),
            ("Satellite Earth Footage", 20),
            ("Thermal Imaging", 12),
            ("Soil Sampling", 10),
            ("Underground Mine", 15),
        ],
    ),
    (
        "Deep Ocean / Ocean Mysteries",
        "deep ocean",
        [
            ("Ocean Surface", 40),
            ("Open Ocean", 35),
            ("Ocean Waves", 35),
            ("Rough Ocean", 20),
            ("Stormy Ocean", 20),
            ("Calm Ocean", 20),
            ("Ocean At Night", 15),
            ("Ocean Drone Footage", 30),
            ("Underwater Ocean", 40),
            ("Deep Underwater", 40),
            ("Dark Ocean", 35),
            ("Underwater Darkness", 30),
            ("Blue Underwater", 30),
            ("Ocean Floor", 45),
            ("Sandy Seafloor", 20),
            ("Rocky Seafloor", 20),
            ("Deep Seafloor", 30),
            ("Underwater Rocks", 20),
            ("Underwater Cliffs", 15),
            ("Underwater Canyon", 15),
            ("Ocean Trench", 30),
            ("Underwater Mountain", 15),
            ("Underwater Volcano", 20),
            ("Hydrothermal Vent", 20),
            ("Black Smoker", 15),
            ("Bubbles Underwater", 15),
            ("Underwater Gas Bubbles", 12),
            ("Underwater Cave", 20),
            ("Underwater Cave Entrance", 15),
            ("Blue Hole", 15),
            ("ROV Underwater", 45),
            ("ROV Descending", 20),
            ("ROV Camera", 15),
            ("ROV Robot Arm", 15),
            ("Underwater Drone", 20),
            ("Submersible", 30),
            ("Submersible Underwater", 30),
            ("Submarine Underwater", 20),
            ("Submarine Surfacing", 12),
            ("Research Ship", 35),
            ("Ocean Research Vessel", 30),
            ("Scientists On Research Ship", 20),
            ("Scientists Launching ROV", 12),
            ("Scientists Recovering ROV", 12),
            ("Marine Scientists", 15),
            ("Ocean Laboratory", 12),
            ("Water Sample Collection", 12),
            ("Sediment Sample", 10),
            ("Underwater Camera", 20),
            ("Underwater Lights", 15),
            ("Divers Underwater", 20),
            ("Deep Sea Diver", 15),
            ("Shipwreck", 30),
            ("Old Shipwreck", 20),
            ("Sunken Ship", 20),
            ("Underwater Aircraft Wreck", 10),
            ("ROV Exploring Shipwreck", 15),
            ("Underwater Ruins", 15),
            ("Underwater Statue", 10),
            ("Submerged Structure", 12),
            ("Coral Reef", 30),
            ("Deep Sea Coral", 15),
            ("Kelp Forest", 15),
            ("School Of Fish", 20),
            ("Shark", 30),
            ("Great White Shark", 20),
            ("Whale Shark", 15),
            ("Whale", 20),
            ("Sperm Whale", 15),
            ("Orca", 15),
            ("Dolphin", 15),
            ("Octopus", 20),
            ("Giant Octopus", 12),
            ("Squid", 15),
            ("Giant Squid", 12),
            ("Jellyfish", 20),
            ("Deep Sea Jellyfish", 15),
            ("Anglerfish", 15),
            ("Deep Sea Fish", 30),
            ("Bioluminescent Creatures", 20),
            ("Bioluminescence Underwater", 20),
            ("Deep Sea Crab", 12),
            ("Giant Isopod", 10),
            ("Sea Cucumber", 10),
            ("Plankton", 12),
            ("Marine Snow", 12),
            ("Ocean Buoy", 12),
            ("Underwater Pipeline", 12),
            ("Undersea Cable", 12),
            ("Offshore Oil Rig", 20),
            ("Iceberg Underwater", 15),
            ("Underwater Ice", 15),
            ("Antarctic Ocean", 20),
            ("Arctic Ocean", 20),
            ("ROV Picking Up Object", 12),
            ("Underwater Sediment Cloud", 12),
            ("Flashlight Underwater", 12),
            ("Object On Seafloor", 15),
            ("Empty Deep Ocean", 20),
            ("Research Vessel At Night", 12),
        ],
    ),
    (
        "Military",
        "US military",
        [
            ("Gerald R. Ford Aircraft Carrier", 45),
            ("Nimitz Class Aircraft Carrier", 45),
            ("Arleigh Burke Class Destroyer", 40),
            ("Zumwalt Class Destroyer", 20),
            ("Virginia Class Submarine", 35),
            ("Ohio Class Submarine", 35),
            ("Los Angeles Class Submarine", 20),
            ("America Class Amphibious Assault Ship", 20),
            ("Wasp Class Amphibious Assault Ship", 20),
            ("San Antonio Class Amphibious Transport Dock", 15),
            ("F/A-18 Super Hornet", 40),
            ("F-35C Lightning II", 35),
            ("E-2D Hawkeye", 20),
            ("P-8 Poseidon", 20),
            ("EA-18G Growler", 20),
            ("MH-60R Seahawk", 20),
            ("V-22 Osprey", 20),
            ("F-35A Lightning II", 40),
            ("F-22 Raptor", 40),
            ("F-16 Fighting Falcon", 35),
            ("F-15E Strike Eagle", 30),
            ("B-2 Spirit", 30),
            ("B-52 Stratofortress", 30),
            ("B-1B Lancer", 20),
            ("A-10 Thunderbolt II", 25),
            ("C-17 Globemaster III", 25),
            ("C-130 Hercules", 25),
            ("KC-135 Stratotanker", 20),
            ("AH-64 Apache", 30),
            ("UH-60 Black Hawk", 30),
            ("CH-47 Chinook", 25),
            ("MH-60 Seahawk", 20),
            ("MQ-9 Reaper", 25),
            ("RQ-4 Global Hawk", 20),
            ("MQ-4C Triton", 15),
            ("Switchblade Drone", 12),
            ("Tomahawk Cruise Missile", 20),
            ("Trident II Missile", 20),
            ("Minuteman III ICBM", 20),
            ("Patriot Missile System", 20),
            ("THAAD Missile System", 15),
            ("HIMARS", 25),
            ("Javelin Missile", 15),
            ("Harpoon Missile", 15),
            ("SM-6 Missile", 12),
            ("M1A2 Abrams Tank", 40),
            ("Bradley Fighting Vehicle", 25),
            ("Stryker Armored Vehicle", 20),
            ("JLTV Military Vehicle", 15),
            ("M109 Paladin Howitzer", 20),
            ("M777 Howitzer", 20),
            ("Phalanx CIWS", 15),
            ("Mark 45 Naval Gun", 15),
            ("Mark 48 Torpedo", 15),
            ("US Navy Sailors", 20),
            ("US Marines", 20),
            ("US Army Soldiers", 20),
            ("Navy SEAL Training", 15),
            ("Naval Base", 20),
            ("Air Force Base", 20),
            ("Military Command Center", 12),
            ("Naval Shipyard", 15),
        ],
    ),
]

# Extra searches stored in the parent folder, not as separate topics.
ANGLES = {
    "Gerald R. Ford Aircraft Carrier": ["sailing", "flight deck", "aircraft launch", "crew", "catapult", "interior"],
    "Nimitz Class Aircraft Carrier": ["sailing", "flight deck", "launch", "landing", "crew"],
    "Arleigh Burke Class Destroyer": ["sailing", "weapons", "missile launch", "bridge", "deck"],
    "Virginia Class Submarine": ["surface", "underwater", "port", "crew"],
    "Ohio Class Submarine": ["surface", "underwater", "missile"],
    "America Class Amphibious Assault Ship": ["aircraft operations", "sailing", "deck"],
    "F/A-18 Super Hornet": ["flying", "carrier takeoff", "carrier landing", "catapult launch", "formation", "cockpit", "deck", "maintenance"],
    "F-35C Lightning II": ["flying", "carrier takeoff", "carrier landing"],
    "E-2D Hawkeye": ["flying", "carrier takeoff"],
    "C-17 Globemaster III": ["flying", "takeoff", "landing", "cargo loading", "paratroopers"],
    "KC-135 Stratotanker": ["flying", "refueling", "refueling F-16", "refueling F-35"],
    "AH-64 Apache": ["flying", "takeoff", "landing", "weapons", "formation"],
    "UH-60 Black Hawk": ["flying", "troops boarding", "troops exiting", "landing", "takeoff"],
    "CH-47 Chinook": ["flying", "cargo lift", "landing"],
    "MH-60 Seahawk": ["flying", "ship landing"],
    "MH-60R Seahawk": ["flying", "ship landing"],
    "MQ-9 Reaper": ["flying", "takeoff"],
    "RQ-4 Global Hawk": ["flying", "takeoff"],
    "Patriot Missile System": ["launcher", "radar", "launch", "crew"],
    "HIMARS": ["driving", "loading", "launch", "crew"],
    "M1A2 Abrams Tank": ["driving", "firing", "loading", "crew", "convoy"],
    "Phalanx CIWS": ["firing"],
    "Mark 45 Naval Gun": ["firing"],
    "Mark 48 Torpedo": ["launch"],
    "US Navy Sailors": ["on deck", "working", "inside ship"],
}
